"""L2: canonical player identities, durable aliases, and manual review."""

from narrative_alpha.identity.crosswalk import (
    DEFAULT_AMBIGUITY_MARGIN,
    DEFAULT_FUZZY_THRESHOLD,
    CrosswalkError,
    PlayerCrosswalk,
)
from narrative_alpha.identity.models import (
    IdentityMatchResult,
    MatchCandidate,
    MatchMethod,
    PlayerIdentityInput,
)
from narrative_alpha.identity.nflverse import (
    NFLVERSE_SOURCE,
    PINNED_ROSTER_RELEASES,
    NflverseRosterError,
    PinnedRosterRelease,
    RosterHashError,
    RosterPlayerChange,
    RosterRefreshReport,
    RosterSchemaError,
    RosterSeedIssue,
    RosterSeedReport,
    fetch_pinned_roster,
    pinned_roster_release,
    refresh_roster_release,
    roster_archive_path,
    seed_nflverse_roster,
)
from narrative_alpha.identity.normalization import (
    CANONICAL_TEAM_CODES,
    TEAM_CODE_ALIASES,
    name_without_suffix,
    normalize_name,
    normalize_team_code,
    team_code_variants,
)
from narrative_alpha.identity.pins import (
    NflversePinError,
    PinHashError,
    PinnedRelease,
    fetch_pinned,
    newest_pin,
    pin_archive_path,
    pinned_release,
)

__all__ = [
    "CANONICAL_TEAM_CODES",
    "DEFAULT_AMBIGUITY_MARGIN",
    "DEFAULT_FUZZY_THRESHOLD",
    "NFLVERSE_SOURCE",
    "PINNED_ROSTER_RELEASES",
    "TEAM_CODE_ALIASES",
    "CrosswalkError",
    "IdentityMatchResult",
    "MatchCandidate",
    "MatchMethod",
    "NflversePinError",
    "NflverseRosterError",
    "PinHashError",
    "PinnedRelease",
    "PinnedRosterRelease",
    "PlayerCrosswalk",
    "PlayerIdentityInput",
    "RosterHashError",
    "RosterPlayerChange",
    "RosterRefreshReport",
    "RosterSchemaError",
    "RosterSeedIssue",
    "RosterSeedReport",
    "fetch_pinned",
    "fetch_pinned_roster",
    "name_without_suffix",
    "newest_pin",
    "normalize_name",
    "normalize_team_code",
    "pin_archive_path",
    "pinned_release",
    "pinned_roster_release",
    "refresh_roster_release",
    "roster_archive_path",
    "seed_nflverse_roster",
    "team_code_variants",
]
