"""L1: SQLite operational store, migrations, and typed row contracts."""

from narrative_alpha.store.connection import StoreConfigurationError, connect_database
from narrative_alpha.store.migrations import (
    DEFAULT_MIGRATIONS_PATH,
    AppliedMigration,
    Migration,
    MigrationDriftError,
    MigrationError,
    apply_migrations,
    discover_migrations,
)
from narrative_alpha.store.models import (
    ActualOwnershipRow,
    AppliedMigrationRow,
    ContestPayoutRow,
    ContestRow,
    DecisionManifestHash,
    DecisionSnapshotRow,
    ExternalPlayerIdRow,
    GameRow,
    ModelRunRow,
    OddsSnapshotRow,
    OwnershipBaselineRow,
    PlayerAliasRow,
    PlayerDistributionCreate,
    PlayerDistributionRow,
    PlayerDistributionSourceRef,
    PlayerRow,
    PlayerTeamHistoryRow,
    ProjectionSnapshotRow,
    ResultRow,
    SalaryRow,
    SlateRow,
    TeamRow,
    UnresolvedPlayerMatchRow,
    WeatherSnapshotRow,
    canonical_distribution_source_set,
    canonical_manifest_hashes,
    distribution_source_set_sha256,
    manifest_hash_set_sha256,
)
from narrative_alpha.store.player_distributions import (
    PlayerDistributionStoreError,
    insert_player_distribution,
)

__all__ = [
    "DEFAULT_MIGRATIONS_PATH",
    "ActualOwnershipRow",
    "AppliedMigration",
    "AppliedMigrationRow",
    "ContestPayoutRow",
    "ContestRow",
    "DecisionManifestHash",
    "DecisionSnapshotRow",
    "ExternalPlayerIdRow",
    "GameRow",
    "Migration",
    "MigrationDriftError",
    "MigrationError",
    "ModelRunRow",
    "OddsSnapshotRow",
    "OwnershipBaselineRow",
    "PlayerAliasRow",
    "PlayerDistributionCreate",
    "PlayerDistributionRow",
    "PlayerDistributionSourceRef",
    "PlayerDistributionStoreError",
    "PlayerRow",
    "PlayerTeamHistoryRow",
    "ProjectionSnapshotRow",
    "ResultRow",
    "SalaryRow",
    "SlateRow",
    "StoreConfigurationError",
    "TeamRow",
    "UnresolvedPlayerMatchRow",
    "WeatherSnapshotRow",
    "apply_migrations",
    "canonical_distribution_source_set",
    "canonical_manifest_hashes",
    "connect_database",
    "discover_migrations",
    "distribution_source_set_sha256",
    "insert_player_distribution",
    "manifest_hash_set_sha256",
]
