"""L3 bounded ownership-offset model, honest evaluation, and scenario artifacts."""

from narrative_alpha.ownership.data import (
    LabelGate,
    MissingTrainingRow,
    OwnershipDataError,
    TrainingData,
    canonical_site,
    load_latest_fit,
    load_scenario_inputs,
    load_training_data,
    persist_fit,
    validate_label_gate,
)
from narrative_alpha.ownership.evaluation import (
    EvaluationFold,
    MetricComparison,
    OwnershipEvaluationError,
    OwnershipEvaluationReport,
    evaluate_forward_chaining,
    persist_evaluation,
    render_evaluation_report,
)
from narrative_alpha.ownership.model import (
    FittedOwnershipModel,
    OwnershipModelError,
    OwnershipScenarioInput,
    OwnershipTrainingRow,
    PosteriorPrediction,
    fit_ownership_model,
    posterior_parameter_draws,
    predict_ownership,
)
from narrative_alpha.ownership.scenarios import (
    OwnershipScenario,
    OwnershipScenarioError,
    ScenarioBuildReport,
    apply_governance_cap,
    build_scenarios,
    calibrate_probabilities,
    persist_scenarios,
)
from narrative_alpha.ownership_config import (
    DEFAULT_OWNERSHIP_CONFIG_PATH,
    CalibrationConfig,
    CapConfig,
    EvaluationConfig,
    GovernanceStatus,
    OwnershipConfigError,
    OwnershipModelConfig,
    PriorConfig,
    load_ownership_config,
)

__all__ = [
    "DEFAULT_OWNERSHIP_CONFIG_PATH",
    "CalibrationConfig",
    "CapConfig",
    "EvaluationConfig",
    "EvaluationFold",
    "FittedOwnershipModel",
    "GovernanceStatus",
    "LabelGate",
    "MetricComparison",
    "MissingTrainingRow",
    "OwnershipConfigError",
    "OwnershipDataError",
    "OwnershipEvaluationError",
    "OwnershipEvaluationReport",
    "OwnershipModelConfig",
    "OwnershipModelError",
    "OwnershipScenario",
    "OwnershipScenarioError",
    "OwnershipScenarioInput",
    "OwnershipTrainingRow",
    "PosteriorPrediction",
    "PriorConfig",
    "ScenarioBuildReport",
    "TrainingData",
    "apply_governance_cap",
    "build_scenarios",
    "calibrate_probabilities",
    "canonical_site",
    "evaluate_forward_chaining",
    "fit_ownership_model",
    "load_latest_fit",
    "load_ownership_config",
    "load_scenario_inputs",
    "load_training_data",
    "persist_evaluation",
    "persist_fit",
    "persist_scenarios",
    "posterior_parameter_draws",
    "predict_ownership",
    "render_evaluation_report",
    "validate_label_gate",
]
