"""L2: salary/projection/result file ingestion and API collectors."""

from narrative_alpha.ingest.projections import (
    OwnershipParseResult,
    ParsedOwnership,
    ParsedProjection,
    ProjectionIngestError,
    ProjectionLoadReport,
    ProjectionParseResult,
    RejectedSourceRow,
    SourceFormat,
    SourceFormatError,
    SourceFormatRegistry,
    SourcePlayerFields,
    load_projection_capture,
)
from narrative_alpha.ingest.results import (
    ContestArchetype,
    ContestLoadReport,
    ContestMetadata,
    ContestSchemaError,
    ContestStandingsError,
    ContestStandingsParseReport,
    ContestStandingsParseResult,
    ParsedActualOwnership,
    RejectedContestRow,
    load_contest_standings,
    parse_contest_standings,
)
from narrative_alpha.ingest.salaries import (
    ParsedSalaryRow,
    RejectedSalaryRow,
    SalaryCsvError,
    SalaryFormat,
    SalaryParseReport,
    SalaryParseResult,
    SalarySchemaError,
    SalarySite,
    SalarySlateType,
    parse_salary_csv,
)

__all__ = [
    "ContestArchetype",
    "ContestLoadReport",
    "ContestMetadata",
    "ContestSchemaError",
    "ContestStandingsError",
    "ContestStandingsParseReport",
    "ContestStandingsParseResult",
    "OwnershipParseResult",
    "ParsedActualOwnership",
    "ParsedOwnership",
    "ParsedProjection",
    "ParsedSalaryRow",
    "ProjectionIngestError",
    "ProjectionLoadReport",
    "ProjectionParseResult",
    "RejectedContestRow",
    "RejectedSalaryRow",
    "RejectedSourceRow",
    "SalaryCsvError",
    "SalaryFormat",
    "SalaryParseReport",
    "SalaryParseResult",
    "SalarySchemaError",
    "SalarySite",
    "SalarySlateType",
    "SourceFormat",
    "SourceFormatError",
    "SourceFormatRegistry",
    "SourcePlayerFields",
    "load_contest_standings",
    "load_projection_capture",
    "parse_contest_standings",
    "parse_salary_csv",
]
